spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      request-timeout: 120000
  application:
    name: family
  httpclient:
    factory: simple
  config:
    import:
      - classpath:ai.yml
      - classpath:data.yml
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000

logging:
  level:
    root: INFO
    rut.uvp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
