services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./app/qdrant_data:/qdrant/storage

  postgres:
    image: postgres:15-alpine
    container_name: family-postgres
    environment:
      POSTGRES_DB: familydb
      POSTGRES_USER: family
      POSTGRES_PASSWORD: family
    ports:
      - "5432:5432"
    volumes:
      - ./app/postgres_data:/var/lib/postgresql/data